channels:
- conda-forge
dependencies:
- python=3.13.2
- pip<=25.0.1
- pip:
  - mlflow==3.7.0
  - cloudpickle==3.1.2
  - numpy==2.2.3
  - pandas==2.2.3
  - psutil==7.0.0
  - pyarrow==22.0.0
  - scikit-learn==1.8.0
  - scipy==1.16.3
  - xgboost==3.1.2
name: mlflow-env
